### PR TITLE
Updated top-page indicators in production

### PR DESCRIPTION
**Pull request by rachelthoms**
Indicator queries, formats, and units updated in the production environment

## Overview

_Please write a description. If the PR is hard to understand, provide a quick explanation of the code._

## Testing instructions
 * How to test this PR
 * Prefer bulleted description
 * Start after checking out this branch
 * Include any setup required, such as bundling scripts, restarting services, etc.
 * Include test case, and expected output

## Jira task / Github issue
_Provide the link to the Jira task(s), if any._

Resolves #XXX

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Checklist before submitting
- [ ] Title: Don't forget to make it clear for everyone, even for people that don't know about the feature/bug.
- [ ] Meaningful commits and code rebased on `develop`.
- [ ] Add entry to CHANGELOG.md, if appropriate

### CODE REVIEW

**Comment by andresgnlez** [comment]
image

This query might need some format 😅

**Comment by andresgnlez** [comment]
image
And this one is returning `2.0163511317091325e-7` 🤔

**Comment by rachelthoms** [comment]
> image
> And this one is returning `2.0163511317091325e-7` 🤔

This is actually correct, and should round out to zero. I think for most countries, this indicator will be very close to zero.

**Comment by rachelthoms** [comment]
> image
> 
> This query might need some format 😅

**Comment by rachelthoms** [comment]
> image
> 
> This query might need some format 😅

This has been fixed!

**Comment by andresgnlez** [comment]
All good! Merging.

**Pull request merged**
