### PR TITLE
Feature/next upgrade

### PR DESCRIPTION
**Pull request by davidsingal**
- Updated next to 4.2.3 version
- Updated React to 16 version
- Moved all defaultProps 
- Removed slick-carousel
- Removed Leaflet and ESRI for leaflet
- Added Leaflet and ESRI for Leaflet using CDN
- Updated other libraries to be compatible with React 16
- Fixed bugs in homepage related to 400 errors and warning

Still missing things:

- [x] Check cards height in explore page

### CODE REVIEW

**Comment by pablopareja** [comment]
I thought that the modals problem was fixed but some of them still don't close: Pulse --> Subscribe to alerts, login modal, etc...
@davidsingal could you have a look at that?

**Comment by davidsingal** [comment]
Updated! @pablopareja

**Comment by pablopareja** [comment]
I still can't close some of the modals, for instance this one:

image

**Comment by pablopareja** [comment]
The Explore page seems to be broken now:
image

```
Uncaught (in promise) Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (invariant.js?5d2c537:42)
    at scheduleWorkImpl (react-dom.development.js?72bfeb0:12125)
    at scheduleWork (react-dom.development.js?72bfeb0:12082)
    at scheduleRootUpdate (react-dom.development.js?72bfeb0:12710)
    at updateContainerAtExpirationTime (react-dom.development.js?72bfeb0:12738)
    at Object.updateContainer (react-dom.development.js?72bfeb0:12765)
    at ReactRoot.webpackJsonp.354.ReactRoot.render (react-dom.development.js?72bfeb0:16069)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js?72bfeb0:16503)
    at react-dom.development.js?72bfeb0:16561
    at Object.unbatchedUpdates (react-dom.development.js?72bfeb0:12557)
    at Object.unmountComponentAtNode (react-dom.development.js?72bfeb0:16560)
    at _callee3$ (index.js?641d572:97)
    at tryCatch (runtime.js?acb8805:62)
    at Generator.invoke [as _invoke] (runtime.js?acb8805:296)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/_next/1524833518455/main.js:7549:21)
    at step (asyncToGenerator.js?659f49f:17)
```

**Comment by davidsingal** [comment]
My fault, I set wrong props in the shared modal component.

**Pull request merged**
