### PR TITLE
My RW profile form

### PR DESCRIPTION
**Pull request by mbarrenechea**
## Overview
- Add avatar (if exists) to header
- Add picture to form
- Remove change password from form

## Pivotal task
https://www.pivotaltracker.com/story/show/152028481

### CODE REVIEW

**Comment by pablopareja** [comment]
I uploaded a picture (in theory successfully) but then I can't see it anywhere even if I log out and log back in again... 🤔

**Comment by pablopareja** [comment]
Could you also please hide the "Delete account" checkbox ?
It shouldn't be there, at least as long as it doesn't work

**Comment by mbarrenechea** [comment]
After checking it I talked with Raul => it's related to the API. So I think it's ready to be merged. He will fix it as soon as posible

**Comment by pablopareja** [comment]
ok 👍

**Pull request merged**
