### PR TITLE
Updates legend timeline styles

### PR DESCRIPTION
**Pull request by andresgnlez**
## Overview
Updates legend timeline styles according to feedback received.
With the new version of the timeline, the default value will be calculated based on the active layer, instead of the first one as it was working before.

## Testing instructions

- Run `yarn` to install latest `vizzuality-components` version, should be `1.3.0`.

- Open http://localhost:9000/data/explore?zoom=4&lat=12.55456352859367&lng=14.23828125&basemap=dark&labels=light&layers=%255B%257B%2522dataset%2522%253A%2522595bcf6f-0343-4146-ba0d-c54b1c928510%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%2522d131bcf4-f1ba-41b6-94bc-0099236e719b%2522%257D%255D&page=1&sort=most-viewed&sortDirection=-1&topics=%255B%2522population%2522%255D to see a dataset with timeline configuration.

Before:
image

After:
image

## Pivotal task
Part of: https://www.pivotaltracker.com/story/show/164251672

---

## Checklist before submitting
- [x] Title: Don't forget to make it clear for everyone, even for people that don't know about the feature/bug.
- [x] Meaningful commits and code rebased on `develop`.

### CODE REVIEW

**Comment by pablopareja** [comment]
@andresgnlez  I have a question regarding the selection handles, why aren't they evenly distributed?
_E.g. in the example that you've shared, the two in the center are closer to each other than to the ones from the extremes._

**Comment by andresgnlez** [comment]
@pablopareja the position of the handles are determined by their value.

**Comment by pablopareja** [comment]
I see, cool then 👍

**Comment by andresgnlez** [comment]
@pablopareja updated the colour of the timeline. Also, added a border around the handler.

**Comment by pablopareja** [comment]
It looks much clearer now 👏 
merging...

**Pull request merged**
